import os, io, platform, sys, socket, time
from time import sleep
from urllib2 import urlopen

mac_address = os.popen("cat /sys/class/net/eth0/address").read()
s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
s.connect(('google.com', 0))
localaddr = s.getsockname()[0] # local subnet
ipaddr = urlopen('http://ip.42.pl/raw').read()
def_gw_device = os.popen("route | grep '^default' | grep -o '[^ ]*$'").read()


def info():
	print ("                          +=====================================================+")
	time.sleep (0.3)
	print ("                                   __    _____  ___    _______   ______    ")
	time.sleep (0.3)
	print ("                                  |' \  (\   \|'   \  /''   ''| /    ' \   ")
	time.sleep (0.3)
	print ("                                  ||  | |.\~   \    |(: ______)// ____  \  ")
	time.sleep (0.3)
	print ("                                  |:  | |: \.   \|  | \/    | /  /    ) :) ")
	time.sleep (0.3)
	print ("                                  |.  | |.  \    \. | // ___)(: (____/ //  ")
	time.sleep (0.3)
	print ("                                  /\  |\|    \    \ |(:  (    \        /   ")
	time.sleep (0.3)
	print ("                                 (__\_|_)\___|\____\) \__/     \=_____/    ")
	time.sleep (0.3)
	print ''                                     
	print ("                          +=====================================================+")
	print ("                                 +------------------------------------+")
	time.sleep (0.3)
	print ("                                   |  Mac Address: " + mac_address)
	time.sleep (0.3)
	print ("                                 +------------------------------------+")
	time.sleep (0.3)
	print ("                                   |  Local address: " + localaddr)
	time.sleep (0.3)
	print ("                                 +------------------------------------+")
	time.sleep (0.3)
	print ("                                   |  IP: " + ipaddr)
	time.sleep (0.3)
	print ("                                 +------------------------------------+")
	time.sleep (0.3)
	print ("                                   |  Operating System: " + platform.system())
	time.sleep (0.3)
	print ("                                 +------------------------------------+")
	time.sleep (0.3)
	print ("                                   |  Name: " + platform.node())
	time.sleep (0.3)
	print ("                                 +------------------------------------+")
	time.sleep (0.3)
	print ("                                   |  Interface: " + def_gw_device)
	time.sleep (0.3)
	print ("                                 +------------------------------------+")
	print ("                         +=======================================================+")
info()
