#!/usr/bin/env python2
# coding: utf-8

#-:-:-:-:-:-:-:-:-:-:-:-:#
#    TIDoS Framework     #
#-:-:-:-:-:-:-:-:-:-:-:-:#

#This module requires TIDoS Framework
#https://github.com/the-Infected-Drake/TIDoS-Framework 

import os
import sys
import time
sys.path.append('core/')
from colors import *

print R+'\n    U N I N S T A L L'
print R+'   ===================\n' 
m = raw_input(O+' [!] Are you sure you want to remove TIDoS (y/N) :> ')
if m == 'y' or 'Y':
    try:
	time.sleep(0.5)
	print GR+' [*] Proceeding towards uninstallation...\n'
	time.sleep(0.4)
	print B+'Removing installation packages for TIDoS-Framework...'+C 
	os.system('rm -v -rf /opt/TIDoS-Framework')
	time.sleep(0.4)
	print B+'Removing setup and executable files...'+C
	time.sleep(0.4)
	os.system('rm -v -rf /usr/bin/tidos')
	time.sleep(0.4)
	print GR+'All installation packages have been removed...\n'
	time.sleep(0.4)
	print G+' [+] TIDoS-Framework has been successfully uninstalled...\n'
    except:
	print R+' [-] Something went wrong!'
else:
	print G+' [+] No probs :)'
	sys.exit(0)
